---
jobs:

- name: configure-pipeline
  serial_groups: [development,staging, production]
  plan:
  - in_parallel:
    - get: pipeline-source
      trigger: true
      params: {depth: 1}
  - set_pipeline: self
    file: pipeline-source/ci/audit-pipeline.yml

- name: monthly-elasticsearch-audit
  serial_groups: [production]
  plan:
  - in_parallel:
    - get: config-source
      trigger: true
    - get: cg-scripts
      trigger: true
  - task: prep-email
    file: config-source/ci/audit/service-instances.yml
    params:
      CF_API_URL: ((prod-cf-api-url))
      CF_USERNAME: ((prod-cf-broker-user.username))
      CF_PASSWORD: ((prod-cf-broker-user.password))
      CF_SERVICE: aws-elasticsearch
  - put: send-an-email
    params:
      subject_text: "AWS Elasticsearch Service Instances"
      body_text: "This is the output for AWS"
      attachment_globs: ["email-out/*.txt"]


resources:

- name: pipeline-source
  type: git
  source:
    uri: https://github.com/cloud-gov/aws-broker
    branch: audit
    paths: [ci/audit-pipeline.yml]

- name: config-source
  type: git
  source:
    uri: https://github.com/cloud-gov/aws-broker
    branch: audit

- name: cg-scripts
  type: git
  source:
    uri: https://github.com/cloud-gov/cg-scripts
    branch: master

- name: send-an-email
  type: email-resource
  source:
    smtp:
      host: ((smtp-host))
      port: ((smtp-port))
      username: ((smtp-cloudgovbilling.username))
      password: ((smtp-cloudgovbilling.password))
      ca_cert: ((smtp-cert.certificate))
    from: ((smtp-email-from))
    to: [((smtp-email-to))]


resource_types:
- name: email-resource
  type: docker-image
  source:
    repository: pcfseceng/email-resource
    tag: latest